export const FETCH_CHEAP_FLIGHTS_REQUEST = "FETCH_CHEAP_FLIGHTS_REQUEST";
export const FETCH_CHEAP_FLIGHTS_SUCCESS = "FETCH_CHEAP_FLIGHTS_SUCCESS";
export const FETCH_CHEAP_FLIGHTS_FAIL = "FETCH_CHEAP_FLIGHTS_FAIL";

export const FETCH_BUSINESS_FLIGHTS_REQUEST = "FETCH_BUSINESS_FLIGHTS_REQUEST";
export const FETCH_BUSINESS_FLIGHTS_SUCCESS = "FETCH_BUSINESS_FLIGHTS_SUCCESS";
export const FETCH_BUSINESS_FLIGHTS_FAIL = "FETCH_BUSINESS_FLIGHTS_FAIL";

export const ADD_BUSINESS_FLIGHTS = "ADD_BUSINESS_FLIGHTS";
export const ADD_CHEAP_FLIGHTS = "ADD_CHEAP_FLIGHTS";
